### ISSUE TITLE
Give option to the player to opt-out permanently from being spammed with the text in the chat.

### ISSUE THREAD

**Issue by dougg0k** [gamemedev/plugin-sourcemod#9]
Literally the title.

Is that possible? 

Because I can disabled temporarily but after reconnecting, it's there again. Also sometimes while connected and after changing maps, it's enabled again, it's random.

**Comment by designstorming** [comment]
I strongly agree. It is just spamming the chat and the server log. We have a gameme profile to look at our stats and at any time we have the `!gameme` command. Also add `AutoExecConfig();` so we can actually configure the plugin.
